server:
  port: 9092

spring:
  data:
    mongodb:
      custom:
        hosts:
          - 192.168.101.217
#          - 10.0.5.1
        ports:
          - 27017
#          - 27018
#        replica-set: mgset-3590061
#        username: jancee
#        password: abc123
        database: testdb
#        authentication-database: admin
        # 客户端连接数
        connections-per-host: 20
        # 客户端最小连接数
        min-connections-per-host: 20
  application:
    name: mongodb-service